import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, '..');
const SOURCE_ROOT = path.resolve(
  REPO_ROOT,
  '..',
  'CS-Self-Leanring-Materials',
  'courses',
  'CS61B',
  '2021Spring'
);
const SOURCE_DOCS_ROOT = path.join(SOURCE_ROOT, 'docs');
const CONTENT_ROOT = path.join(
  REPO_ROOT,
  'src',
  'content',
  'docs',
  'cs61b',
  '2021spring'
);
const ASSET_ROOT = path.join(
  REPO_ROOT,
  'public',
  'docs-assets',
  'cs61b',
  '2021spring',
  'assets'
);
const MKDOCS_PATH = path.join(SOURCE_ROOT, 'mkdocs.yml');
const MANIFEST_PATH = path.join(CONTENT_ROOT, '.cs61b-import-manifest.json');

const ASSET_URL_PREFIX = '/docs-assets/cs61b/2021spring/assets/';
const NEW_DOCS_URL_PREFIX = '/docs/cs61b/2021spring';
const OLD_DOCS_URL_PREFIX = '/CS61B/2021Spring';
const IMPORT_MARKER =
  '<!-- Generated by scripts/import-cs61b.mjs. Do not edit. -->';
const ATTRIBUTION_START = '<!-- CS61B_IMPORT_ATTRIBUTION_START -->';
const ATTRIBUTION_END = '<!-- CS61B_IMPORT_ATTRIBUTION_END -->';
const ATTRIBUTION_NOTICE = [
  ATTRIBUTION_START,
  '> 原作：Josh Hug，UC Berkeley CS61B Spring 2021。',
  '> 中文整理：everlasting。',
  '> 本翻译整理内容采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可。',
  '> 原始课程网站：[CS61B Spring 2021](https://sp21.datastructur.es/)；原始读本：[Hug61B](https://joshhug.gitbooks.io/hug61b/content/)。',
  ATTRIBUTION_END
].join('\n');
const MANIFEST_MARKER = 'astro-theme-pure/cs61b-import';
const MANIFEST_VERSION = 1;

// 这些页面仍保留在只读源仓库中，但按当前博客发布范围不导入。
const EXCLUDED_SOURCE_PATHS = new Set(['index.md', 'about.md']);
const EXCLUDED_NAV_SECTIONS = new Set(['作业', '考试']);
const EXCLUDED_SOURCE_PREFIXES = new Set(['homeworks', 'exams']);

const EXPECTED_SOURCE_PAGE_COUNT = 53;
const EXPECTED_PAGE_COUNT = 42;
const EXPECTED_IMAGE_REFERENCE_COUNT = 241;
const EXPECTED_REFERENCED_ASSET_COUNT = 240;
const EXPECTED_HEADING_ID_COUNT = 191;
const EXPECTED_REMOVED_FIRST_H1_COUNT = 41;
// The audit records 7 source lines, while those lines contain 11 actual
// attribute lists. The importer removes and records each actual list.
const EXPECTED_REMOVED_LINK_ATTRIBUTE_COUNT = 0;
const EXPECTED_REMOVED_MARKDOWN_ATTRIBUTE_COUNT = 0;

const EXPECTED_NAV_SECTIONS = new Map([
  ['首页', 1],
  ['中文课程主页', 1],
  ['课程教材', 22],
  ['实验', 12],
  ['作业', 4],
  ['项目', 7],
  ['考试', 5],
  ['关于与许可', 1]
]);

function fail(message) {
  throw new Error(message);
}

function normalizeNewlines(text) {
  return text.replace(/\r\n?/g, '\n');
}

function toPosix(value) {
  return value.replace(/\\/g, '/');
}

function compareStrings(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

function isWithin(root, target) {
  const relative = path.relative(path.resolve(root), path.resolve(target));
  return relative === '' || (relative !== '..' && !relative.startsWith('..' + path.sep) && !path.isAbsolute(relative));
}

function safeResolve(root, relativePath) {
  if (typeof relativePath !== 'string' || path.isAbsolute(relativePath)) {
    fail('拒绝使用不安全的绝对路径：' + String(relativePath));
  }
  const target = path.resolve(root, relativePath);
  if (!isWithin(root, target)) {
    fail('拒绝越界路径：' + relativePath);
  }
  return target;
}

function readUtf8(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

function normalizeSourcePath(value, label) {
  if (typeof value !== 'string') {
    fail(label + ' 不是字符串：' + String(value));
  }
  const normalizedSlashes = toPosix(value).replace(/^\.\/+/, '');
  const normalized = path.posix.normalize(normalizedSlashes);
  if (
    normalized === '.' ||
    normalized.startsWith('../') ||
    normalized === '..' ||
    normalized.startsWith('/') ||
    !normalized.toLowerCase().endsWith('.md')
  ) {
    fail(label + ' 不是 docs 内的 Markdown 路径：' + value);
  }
  return normalized;
}

export function walkFiles(root) {
  if (!fs.existsSync(root)) {
    return [];
  }
  if (!fs.lstatSync(root).isDirectory()) {
    fail('预期目录不存在或不是目录：' + root);
  }
  const result = [];
  function visit(directory) {
    const entries = fs
      .readdirSync(directory, { withFileTypes: true })
      .sort((left, right) => compareStrings(left.name, right.name));
    for (const entry of entries) {
      const absolute = path.join(directory, entry.name);
      if (entry.isDirectory()) {
        visit(absolute);
      } else if (entry.isFile()) {
        result.push(toPosix(path.relative(root, absolute)));
      }
    }
  }
  visit(root);
  return result;
}

function parseFenceMarker(line) {
  const match = line.match(/^\s*(\x60{3,}|~{3,})/);
  if (!match) {
    return null;
  }
  return { char: match[1][0], length: match[1].length };
}

function isFenceClose(line, fence) {
  const match = line.match(/^\s*(\x60{3,}|~{3,})\s*$/);
  return Boolean(
    match &&
      match[1][0] === fence.char &&
      match[1].length >= fence.length
  );
}

export function forEachOutsideFence(text, callback) {
  const lines = normalizeNewlines(text).split('\n');
  let fence = null;
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    const marker = parseFenceMarker(line);
    if (fence) {
      if (isFenceClose(line, fence)) {
        fence = null;
      }
      continue;
    }
    if (marker) {
      fence = marker;
      continue;
    }
    callback(line, index);
  }
}

export function parseFrontmatter(text, label) {
  const normalized = normalizeNewlines(text);
  if (!normalized.startsWith('---\n')) {
    return { values: {}, body: normalized };
  }
  const match = normalized.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!match) {
    fail('Frontmatter 未闭合：' + label);
  }
  const values = parseYaml(match[1]) ?? {};
  if (typeof values !== 'object' || Array.isArray(values)) {
    fail('Frontmatter 必须是 YAML 对象：' + label);
  }
  return {
    values,
    body: normalized.slice(match[0].length)
  };
}

function cleanHeadingText(text) {
  return text.replace(/\s+\{\s*#[^}\s]+\s*\}\s*$/, '').trim();
}

function parseHeading(line) {
  const match = line.match(/^(\s{0,3})(#{1,6})[ \t]+(.+?)\s*$/);
  if (!match) {
    return null;
  }
  const text = match[3].trim();
  const idMatch = text.match(/\s+\{\s*#([^}\s]+)\s*\}\s*$/);
  return {
    indent: match[1],
    hashes: match[2],
    level: match[2].length,
    text,
    cleanText: cleanHeadingText(text),
    explicitId: idMatch ? idMatch[1] : null
  };
}

export function findFirstH1(body) {
  let result = null;
  forEachOutsideFence(body, (line, lineIndex) => {
    if (result) {
      return;
    }
    const heading = parseHeading(line);
    if (heading && heading.level === 1) {
      result = {
        lineIndex,
        title: heading.cleanText,
        explicitId: heading.explicitId
      };
    }
  });
  return result;
}

function escapeHtmlAttribute(value) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/'/g, '&#39;');
}

function parseLinkAt(line, start, isImage) {
  const openingBracket = start + (isImage ? 1 : 0);
  if (line[openingBracket] !== '[') {
    return null;
  }
  let bracketDepth = 1;
  let closingBracket = -1;
  for (let index = openingBracket + 1; index < line.length; index += 1) {
    const character = line[index];
    if (character === '\\') {
      index += 1;
      continue;
    }
    if (character === '[') {
      bracketDepth += 1;
    } else if (character === ']') {
      bracketDepth -= 1;
      if (bracketDepth === 0) {
        closingBracket = index;
        break;
      }
    }
  }
  if (closingBracket < 0) {
    return null;
  }
  let openingParenthesis = closingBracket + 1;
  while (/\s/.test(line[openingParenthesis] || '')) {
    openingParenthesis += 1;
  }
  if (line[openingParenthesis] !== '(') {
    return null;
  }
  let parenthesisDepth = 1;
  let closingParenthesis = -1;
  for (let index = openingParenthesis + 1; index < line.length; index += 1) {
    const character = line[index];
    if (character === '\\') {
      index += 1;
      continue;
    }
    if (character === '(') {
      parenthesisDepth += 1;
    } else if (character === ')') {
      parenthesisDepth -= 1;
      if (parenthesisDepth === 0) {
        closingParenthesis = index;
        break;
      }
    }
  }
  if (closingParenthesis < 0) {
    return null;
  }
  return {
    start,
    labelStart: openingBracket + 1,
    labelEnd: closingBracket,
    targetStart: openingParenthesis + 1,
    targetEnd: closingParenthesis,
    target: line.slice(openingParenthesis + 1, closingParenthesis),
    end: closingParenthesis + 1,
    isImage
  };
}

export function findInlineLinks(line) {
  const links = [];
  for (let index = 0; index < line.length; index += 1) {
    if (line.startsWith('![', index)) {
      const image = parseLinkAt(line, index, true);
      if (image) {
        links.push(image);
        index = image.end - 1;
      }
      continue;
    }
    if (line[index] === '[' && (index === 0 || line[index - 1] !== '!')) {
      const link = parseLinkAt(line, index, false);
      if (link) {
        links.push(link);
      }
    }
  }
  return links;
}

export function findHtmlAttributes(line) {
  const attributes = [];
  const pattern = /\b(href|src)\s*=\s*(["'])([^"']*)\2/gi;
  let match;
  while ((match = pattern.exec(line)) !== null) {
    const quoteIndex = match[0].indexOf(match[2]);
    const targetStart = match.index + quoteIndex + 1;
    attributes.push({
      name: match[1].toLowerCase(),
      target: match[3],
      targetStart,
      targetEnd: targetStart + match[3].length
    });
  }
  return attributes;
}

export function findHtmlImages(line) {
  const images = [];
  const pattern = /<img\b[^>]*\bsrc\s*=\s*(["'])([^"']*)\1/gi;
  let match;
  while ((match = pattern.exec(line)) !== null) {
    images.push({ target: match[2] });
  }
  return images;
}

function splitUrlSuffix(url) {
  const queryIndex = url.indexOf('?');
  const hashIndex = url.indexOf('#');
  let splitIndex = -1;
  if (queryIndex >= 0 && hashIndex >= 0) {
    splitIndex = Math.min(queryIndex, hashIndex);
  } else {
    splitIndex = Math.max(queryIndex, hashIndex);
  }
  if (splitIndex < 0) {
    return { pathPart: url, suffix: '' };
  }
  return {
    pathPart: url.slice(0, splitIndex),
    suffix: url.slice(splitIndex)
  };
}

function isExternalUrl(url) {
  return /^[A-Za-z][A-Za-z0-9+.-]*:/.test(url) || url.startsWith('//');
}

function extractMarkdownDestination(raw) {
  const leading = raw.match(/^\s*/)[0];
  const value = raw.slice(leading.length);
  if (value.startsWith('<')) {
    const closing = value.indexOf('>');
    if (closing >= 0) {
      return {
        leading,
        destination: value.slice(1, closing),
        wrapper: 'angle',
        rest: value.slice(closing + 1)
      };
    }
  }
  const match = value.match(/^(\S+)([\s\S]*)$/);
  if (!match) {
    return { leading, destination: '', wrapper: 'plain', rest: '' };
  }
  return {
    leading,
    destination: match[1],
    wrapper: 'plain',
    rest: match[2]
  };
}

function rewriteMarkdownTarget(raw, fromSourcePath, referencedAssets, isImage) {
  const parsed = extractMarkdownDestination(raw);
  if (!parsed.destination) {
    return raw;
  }
  const rewritten = rewriteTarget(
    parsed.destination,
    fromSourcePath,
    referencedAssets,
    isImage
  );
  const destination =
    parsed.wrapper === 'angle' ? '<' + rewritten + '>' : rewritten;
  return parsed.leading + destination + parsed.rest;
}

function resolveSourceRelative(fromSourcePath, targetPath) {
  const candidate = targetPath.startsWith('/')
    ? targetPath.slice(1)
    : path.posix.join(path.posix.dirname(fromSourcePath), targetPath);
  const normalized = path.posix.normalize(candidate);
  if (
    normalized === '.' ||
    normalized.startsWith('../') ||
    normalized === '..' ||
    normalized.startsWith('/')
  ) {
    fail(
      '链接越出 CS61B docs 根目录：' +
        fromSourcePath +
        ' -> ' +
        targetPath
    );
  }
  return normalized;
}

function sourceAssetPathForTarget(fromSourcePath, targetPath) {
  const sourcePath = resolveSourceRelative(fromSourcePath, targetPath);
  if (!sourcePath.startsWith('assets/')) {
    return null;
  }
  const outputPath = sourcePath.slice('assets/'.length);
  if (!outputPath || outputPath.startsWith('../')) {
    fail('非法 CS61B 资源路径：' + targetPath);
  }
  return {
    sourcePath,
    outputPath
  };
}

function routeForSourcePath(sourcePath) {
  const normalized = normalizeSourcePath(sourcePath, '源 Markdown 路径');
  const withoutExtension = normalized.slice(0, -3);
  if (withoutExtension === 'index') {
    return NEW_DOCS_URL_PREFIX + '/';
  }
  if (withoutExtension.endsWith('/index')) {
    return (
      NEW_DOCS_URL_PREFIX +
      '/' +
      withoutExtension.slice(0, -'/index'.length) +
      '/'
    );
  }
  return NEW_DOCS_URL_PREFIX + '/' + withoutExtension + '/';
}

function assetUrlForPath(outputPath) {
  return ASSET_URL_PREFIX + outputPath;
}

function sourcePathFromLegacyDocsPath(oldRelative) {
  const trimmed = oldRelative.replace(/^\/+|\/+$/g, '');
  const candidates = trimmed
    ? [trimmed + '.md', trimmed + '/index.md']
    : ['index.md'];
  for (const candidate of candidates) {
    const normalized = normalizeSourcePath(candidate, '旧站 CS61B 路径');
    const absolute = safeResolve(SOURCE_DOCS_ROOT, normalized);
    if (fs.existsSync(absolute) && fs.statSync(absolute).isFile()) {
      return normalized;
    }
  }
  return null;
}

function sourcePathFromTarget(target, fromSourcePath) {
  const destination = extractMarkdownDestination(target).destination;
  if (!destination || isExternalUrl(destination) || destination.startsWith('#')) {
    return null;
  }
  const pathPart = splitUrlSuffix(destination).pathPart;
  if (
    pathPart === OLD_DOCS_URL_PREFIX ||
    pathPart.startsWith(OLD_DOCS_URL_PREFIX + '/')
  ) {
    return sourcePathFromLegacyDocsPath(
      pathPart.slice(OLD_DOCS_URL_PREFIX.length)
    );
  }
  if (pathPart.toLowerCase().endsWith('.md')) {
    return resolveSourceRelative(fromSourcePath, pathPart);
  }
  return null;
}

function isExcludedSourcePath(sourcePath) {
  return (
    EXCLUDED_SOURCE_PATHS.has(sourcePath) ||
    Array.from(EXCLUDED_SOURCE_PREFIXES).some(
      (section) =>
        sourcePath === section + '.md' || sourcePath.startsWith(section + '/')
    )
  );
}

function isExcludedTarget(target, fromSourcePath) {
  const sourcePath = sourcePathFromTarget(target, fromSourcePath);
  return Boolean(sourcePath && isExcludedSourcePath(sourcePath));
}

function stripExcludedHtmlLinks(line, fromSourcePath) {
  return line.replace(
    /<a\b([^>]*)>([\s\S]*?)<\/a>/gi,
    (full, attributes, content) => {
      const href = attributes.match(/\bhref\s*=\s*(['"])([^'"]*)\1/i);
      return href && isExcludedTarget(href[2], fromSourcePath)
        ? content
        : full;
    }
  );
}

function rewriteTarget(target, fromSourcePath, referencedAssets, isImage) {
  if (!target || isExternalUrl(target) || target.startsWith('#')) {
    return target;
  }
  const split = splitUrlSuffix(target);
  const pathPart = split.pathPart;
  const suffix = split.suffix;
  if (pathPart === '/') {
    return '/docs/' + suffix;
  }
  if (
    pathPart === OLD_DOCS_URL_PREFIX ||
    pathPart.startsWith(OLD_DOCS_URL_PREFIX + '/')
  ) {
    const oldRelative = pathPart
      .slice(OLD_DOCS_URL_PREFIX.length)
      .replace(/^\/+/, '');
    if (!oldRelative) {
      return NEW_DOCS_URL_PREFIX + '/' + suffix;
    }
    if (oldRelative.toLowerCase().endsWith('.md')) {
      return (
        routeForSourcePath(normalizeSourcePath(oldRelative, '旧站 Markdown 链接')) +
        suffix
      );
    }
    const normalizedOld = oldRelative.replace(/\/index\/?$/, '/');
    return NEW_DOCS_URL_PREFIX + '/' + normalizedOld.replace(/^\/+/, '') + suffix;
  }

  const asset = sourceAssetPathForTarget(fromSourcePath, pathPart);
  if (asset) {
    const fullSourcePath = safeResolve(SOURCE_DOCS_ROOT, asset.sourcePath);
    if (!fs.existsSync(fullSourcePath) || !fs.statSync(fullSourcePath).isFile()) {
      fail(
        '源文档引用了不存在的资源：' +
          fromSourcePath +
          ' -> ' +
          pathPart
      );
    }
    if (referencedAssets.has(asset.outputPath)) {
      return assetUrlForPath(asset.outputPath) + suffix;
    }
    if (isImage) {
      fail('图片没有进入引用资源集合：' + fromSourcePath + ' -> ' + pathPart);
    }
    return target;
  }

  if (pathPart.toLowerCase().endsWith('.md')) {
    const sourcePath = resolveSourceRelative(fromSourcePath, pathPart);
    return routeForSourcePath(sourcePath) + suffix;
  }
  return target;
}

function stripLinkAttributeLists(line) {
  let count = 0;
  const result = line.replace(
    /(\]\([^)\n]*\))\s*\{[^}\n]+\}/g,
    (_full, link) => {
      count += 1;
      return link;
    }
  );
  return { line: result, count };
}

function stripMarkdownHtmlAttributes(line) {
  let count = 0;
  const result = line.replace(/<([A-Za-z][^>]*)>/g, (_full, inside) => {
    const stripped = inside.replace(
      /\s+markdown(?:\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+))?(?=\s|\/?$)/gi,
      () => {
        count += 1;
        return '';
      }
    );
    return '<' + stripped + '>';
  });
  return { line: result, count };
}

function rewriteLine(line, fromSourcePath, referencedAssets) {
  const replacements = [];
  for (const link of findInlineLinks(line)) {
    if (!link.isImage && isExcludedTarget(link.target, fromSourcePath)) {
      replacements.push({
        start: link.start,
        end: link.end,
        value: line.slice(link.labelStart, link.labelEnd)
      });
      continue;
    }
    const rewritten = rewriteMarkdownTarget(
      link.target,
      fromSourcePath,
      referencedAssets,
      link.isImage
    );
    if (rewritten !== link.target) {
      replacements.push({
        start: link.targetStart,
        end: link.targetEnd,
        value: rewritten
      });
    }
  }
  for (const attribute of findHtmlAttributes(line)) {
    if (
      attribute.name === 'href' &&
      isExcludedTarget(attribute.target, fromSourcePath)
    ) {
      continue;
    }
    const rewritten = rewriteTarget(
      attribute.target,
      fromSourcePath,
      referencedAssets,
      attribute.name === 'src'
    );
    if (rewritten !== attribute.target) {
      replacements.push({
        start: attribute.targetStart,
        end: attribute.targetEnd,
        value: rewritten
      });
    }
  }
  let result = line;
  replacements
    .sort((left, right) => right.start - left.start)
    .forEach((replacement) => {
      result =
        result.slice(0, replacement.start) +
        replacement.value +
      result.slice(replacement.end);
    });
  const links = stripLinkAttributeLists(
    stripExcludedHtmlLinks(result, fromSourcePath)
  );
  const html = stripMarkdownHtmlAttributes(links.line);
  return {
    line: html.line,
    removedLinkAttributes: links.count,
    removedMarkdownAttributes: html.count
  };
}

export function renderBody(body, sourcePath, referencedAssets) {
  const normalized = normalizeNewlines(body);
  const firstH1 = findFirstH1(normalized);
  const lines = normalized.split('\n');
  const output = [];
  const headingIds = [];
  let removedFirstH1 = false;
  let removedLinkAttributes = 0;
  let removedMarkdownAttributes = 0;
  let fence = null;

  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    const marker = parseFenceMarker(line);
    if (fence) {
      output.push(line);
      if (isFenceClose(line, fence)) {
        fence = null;
      }
      continue;
    }
    if (marker) {
      output.push(line);
      fence = marker;
      continue;
    }

    const heading = parseHeading(line);
    if (heading) {
      const isFirstH1 = Boolean(
        firstH1 && firstH1.lineIndex === index && heading.level === 1
      );
      if (heading.explicitId) {
        headingIds.push(heading.explicitId);
        output.push('<a id="' + escapeHtmlAttribute(heading.explicitId) + '"></a>');
      }
      if (isFirstH1) {
        removedFirstH1 = true;
        continue;
      }
      const headingLine =
        heading.indent +
        heading.hashes +
        ' ' +
        heading.cleanText;
      const rewrittenHeading = rewriteLine(
        heading.explicitId ? headingLine : line,
        sourcePath,
        referencedAssets
      );
      output.push(rewrittenHeading.line);
      removedLinkAttributes += rewrittenHeading.removedLinkAttributes;
      removedMarkdownAttributes += rewrittenHeading.removedMarkdownAttributes;
      continue;
    }

    const rewritten = rewriteLine(line, sourcePath, referencedAssets);
    output.push(rewritten.line);
    removedLinkAttributes += rewritten.removedLinkAttributes;
    removedMarkdownAttributes += rewritten.removedMarkdownAttributes;
  }

  return {
    body: output.join('\n').replace(/\n+$/, ''),
    headingIds,
    firstH1Removed: removedFirstH1,
    removedLinkAttributes,
    removedMarkdownAttributes
  };
}

function flattenNavigation(node, labels, result) {
  if (Array.isArray(node)) {
    for (const item of node) {
      flattenNavigation(item, labels, result);
    }
    return;
  }
  if (typeof node === 'string') {
    result.push({
      sourcePath: normalizeSourcePath(node, 'mkdocs.yml 导航项'),
      labels,
      section: labels[0] || ''
    });
    return;
  }
  if (!node || typeof node !== 'object') {
    fail('mkdocs.yml 导航项不是字符串、数组或对象：' + String(node));
  }
  for (const [label, value] of Object.entries(node)) {
    flattenNavigation(value, labels.concat(label), result);
  }
}

function validateSourceInventory(navigation) {
  if (navigation.length !== EXPECTED_SOURCE_PAGE_COUNT) {
    fail(
      'mkdocs.yml 导航叶子数量不符合审计结果：' +
        navigation.length +
        '，预期 ' +
        EXPECTED_SOURCE_PAGE_COUNT
    );
  }
  const navigationPaths = navigation.map((entry) => entry.sourcePath);
  const duplicates = navigationPaths.filter(
    (sourcePath, index) => navigationPaths.indexOf(sourcePath) !== index
  );
  if (duplicates.length > 0) {
    fail('mkdocs.yml 存在重复导航文件：' + duplicates.join(', '));
  }
  const sourcePaths = walkFiles(SOURCE_DOCS_ROOT)
    .filter((filePath) => filePath.toLowerCase().endsWith('.md'))
    .map((filePath) => normalizeSourcePath(filePath, '源 Markdown 文件'))
    .sort(compareStrings);
  const navSet = new Set(navigationPaths);
  const sourceSet = new Set(sourcePaths);
  const missing = navigationPaths.filter((sourcePath) => !sourceSet.has(sourcePath));
  const orphaned = sourcePaths.filter((sourcePath) => !navSet.has(sourcePath));
  if (missing.length > 0 || orphaned.length > 0) {
    fail(
      '导航与源 Markdown 清单不一致；缺失：' +
        (missing.join(', ') || '无') +
        '；孤儿文件：' +
        (orphaned.join(', ') || '无')
    );
  }
  const counts = new Map();
  for (const entry of navigation) {
    counts.set(entry.section, (counts.get(entry.section) || 0) + 1);
  }
  for (const [section, expected] of EXPECTED_NAV_SECTIONS) {
    if (counts.get(section) !== expected) {
      fail(
        '导航分组数量不符合审计结果：' +
          section +
          ' 为 ' +
          String(counts.get(section) || 0) +
          '，预期 ' +
          expected
      );
    }
  }
  if (counts.size !== EXPECTED_NAV_SECTIONS.size) {
    fail('mkdocs.yml 出现审计范围外的顶层导航分组。');
  }
}

function loadSourcePages() {
  if (!fs.existsSync(SOURCE_ROOT) || !fs.statSync(SOURCE_ROOT).isDirectory()) {
    fail('找不到只读源仓库课程目录：' + SOURCE_ROOT);
  }
  const mkdocs = parseYaml(readUtf8(MKDOCS_PATH));
  if (!mkdocs || typeof mkdocs !== 'object' || !mkdocs.nav) {
    fail('mkdocs.yml 缺少可解析的 nav：' + MKDOCS_PATH);
  }
  const navigation = [];
  flattenNavigation(mkdocs.nav, [], navigation);
  validateSourceInventory(navigation);
  const importedNavigation = navigation.filter(
    (entry) =>
      !EXCLUDED_SOURCE_PATHS.has(entry.sourcePath) &&
      !EXCLUDED_NAV_SECTIONS.has(entry.section)
  );

  return importedNavigation.map((entry, index) => {
    const sourceAbsolute = safeResolve(SOURCE_DOCS_ROOT, entry.sourcePath);
    if (!fs.existsSync(sourceAbsolute) || !fs.statSync(sourceAbsolute).isFile()) {
      fail('导航文件不是可读文件：' + sourceAbsolute);
    }
    const parsed = parseFrontmatter(
      readUtf8(sourceAbsolute),
      entry.sourcePath
    );
    const firstH1 = findFirstH1(parsed.body);
    const title =
      typeof parsed.values.title === 'string'
        ? parsed.values.title
        : firstH1
          ? firstH1.title
          : '';
    if (!title) {
      fail('无法从 frontmatter 或第一个 H1 推导标题：' + entry.sourcePath);
    }
    if (title.length > 60) {
      fail('标题超过 Astro schema 限制：' + entry.sourcePath);
    }
    if (typeof parsed.values.description !== 'string') {
      fail('源页面缺少 description：' + entry.sourcePath);
    }
    if (parsed.values.description.length > 160) {
      fail('description 超过 Astro schema 限制：' + entry.sourcePath);
    }
    const supportedKeys = new Set(['title', 'description']);
    const removedFrontmatterKeys = Object.keys(parsed.values)
      .filter((key) => !supportedKeys.has(key))
      .sort(compareStrings);
    const removedFrontmatter = {};
    for (const key of removedFrontmatterKeys) {
      removedFrontmatter[key] = parsed.values[key];
    }
    return {
      sourcePath: entry.sourcePath,
      sourceAbsolute,
      labels: entry.labels,
      section: entry.section,
      order: index + 1,
      title,
      description: parsed.values.description,
      body: parsed.body,
      removedFrontmatterKeys,
      removedFrontmatter
    };
  });
}

function collectReferencedAssets(pages) {
  const counts = new Map();
  let imageReferences = 0;
  function addReference(page, target) {
    const destination = splitUrlSuffix(target).pathPart;
    if (!destination || isExternalUrl(destination) || destination.startsWith('#')) {
      return;
    }
    const asset = sourceAssetPathForTarget(page.sourcePath, destination);
    if (!asset) {
      return;
    }
    const sourceAbsolute = safeResolve(SOURCE_DOCS_ROOT, asset.sourcePath);
    if (
      !fs.existsSync(sourceAbsolute) ||
      !fs.statSync(sourceAbsolute).isFile()
    ) {
      fail(
        '源文档引用了不存在的图片资源：' +
          page.sourcePath +
          ' -> ' +
          target
      );
    }
    counts.set(asset.outputPath, (counts.get(asset.outputPath) || 0) + 1);
  }

  for (const page of pages) {
    forEachOutsideFence(page.body, (line) => {
      for (const link of findInlineLinks(line)) {
        if (link.isImage) {
          imageReferences += 1;
          const parsed = extractMarkdownDestination(link.target);
          addReference(page, parsed.destination);
        }
      }
      for (const image of findHtmlImages(line)) {
        imageReferences += 1;
        addReference(page, image.target);
      }
    });
  }

  const assets = Array.from(counts.entries())
    .sort((left, right) => compareStrings(left[0], right[0]))
    .map(([outputPath, count]) => ({
      path: outputPath,
      sourcePath: 'assets/' + outputPath,
      count,
      sourceAbsolute: safeResolve(
        SOURCE_DOCS_ROOT,
        'assets/' + outputPath
      )
    }));
  return { assets, imageReferences };
}

function makeFrontmatter(page) {
  return stringifyYaml(
    {
      title: page.title,
      description: page.description,
      order: page.order
    },
    { lineWidth: 0 }
  ).trimEnd();
}

function makePageContent(page, rendered) {
  const sections = [
    '---',
    makeFrontmatter(page),
    '---',
    '',
    IMPORT_MARKER,
    ''
  ];
  if (rendered.body) {
    sections.push(rendered.body, '');
  }
  sections.push(ATTRIBUTION_NOTICE);
  return sections.join('\n') + '\n';
}

function buildManifest(pages, assets, imageReferences, renderStats) {
  return {
    marker: MANIFEST_MARKER,
    version: MANIFEST_VERSION,
    source: {
      root: toPosix(path.relative(REPO_ROOT, SOURCE_ROOT)),
      docs: toPosix(path.relative(REPO_ROOT, SOURCE_DOCS_ROOT)),
      mkdocs: toPosix(path.relative(REPO_ROOT, MKDOCS_PATH))
    },
    destination: {
      contentRoot: toPosix(path.relative(REPO_ROOT, CONTENT_ROOT)),
      assetRoot: toPosix(path.relative(REPO_ROOT, ASSET_ROOT)),
      assetUrlPrefix: ASSET_URL_PREFIX
    },
    counts: {
      pages: pages.length,
      imageReferences,
      referencedAssets: assets.length,
      headingIds: renderStats.headingIds,
      removedFirstH1: renderStats.removedFirstH1,
      removedLinkAttributes: renderStats.removedLinkAttributes,
      removedMarkdownAttributes: renderStats.removedMarkdownAttributes
    },
    navigation: pages.map((page) => ({
      order: page.order,
      source: page.sourcePath,
      labels: page.labels
    })),
    pages: pages.map((page) => ({
      source: page.sourcePath,
      output: toPosix(path.relative(CONTENT_ROOT, page.outputAbsolute)),
      route: page.route,
      section: page.section,
      order: page.order,
      title: page.title,
      removedFrontmatterKeys: page.removedFrontmatterKeys,
      removedFrontmatter: page.removedFrontmatter,
      firstH1Removed: page.rendered.firstH1Removed,
      headingIds: page.rendered.headingIds
    })),
    assets: assets.map((asset) => asset.path)
  };
}

export function buildPlan() {
  const sourcePages = loadSourcePages();
  const collected = collectReferencedAssets(sourcePages);
  if (collected.imageReferences !== EXPECTED_IMAGE_REFERENCE_COUNT) {
    fail(
      '图片引用次数不符合审计结果：' +
        collected.imageReferences +
        '，预期 ' +
        EXPECTED_IMAGE_REFERENCE_COUNT
    );
  }
  if (collected.assets.length !== EXPECTED_REFERENCED_ASSET_COUNT) {
    fail(
      '被引用资源数量不符合审计结果：' +
        collected.assets.length +
        '，预期 ' +
        EXPECTED_REFERENCED_ASSET_COUNT
    );
  }
  const referencedAssets = new Set(collected.assets.map((asset) => asset.path));
  const pages = sourcePages.map((page) => {
    const rendered = renderBody(page.body, page.sourcePath, referencedAssets);
    const outputAbsolute = safeResolve(CONTENT_ROOT, page.sourcePath);
    return {
      ...page,
      outputAbsolute,
      route: routeForSourcePath(page.sourcePath),
      rendered,
      content: makePageContent(page, rendered)
    };
  });
  const renderStats = pages.reduce(
    (stats, page) => ({
      headingIds: stats.headingIds + page.rendered.headingIds.length,
      removedFirstH1:
        stats.removedFirstH1 + (page.rendered.firstH1Removed ? 1 : 0),
      removedLinkAttributes:
        stats.removedLinkAttributes + page.rendered.removedLinkAttributes,
      removedMarkdownAttributes:
        stats.removedMarkdownAttributes + page.rendered.removedMarkdownAttributes
    }),
    {
      headingIds: 0,
      removedFirstH1: 0,
      removedLinkAttributes: 0,
      removedMarkdownAttributes: 0
    }
  );
  if (pages.length !== EXPECTED_PAGE_COUNT) {
    fail('生成页面数量不符合审计结果。');
  }
  if (renderStats.headingIds !== EXPECTED_HEADING_ID_COUNT) {
    fail(
      '显式标题锚点数量不符合审计结果：' +
        renderStats.headingIds +
        '，预期 ' +
        EXPECTED_HEADING_ID_COUNT
    );
  }
  if (renderStats.removedFirstH1 !== EXPECTED_REMOVED_FIRST_H1_COUNT) {
    fail(
      '被移除的首个 H1 数量不符合审计结果：' +
        renderStats.removedFirstH1 +
        '，预期 ' +
        EXPECTED_REMOVED_FIRST_H1_COUNT
    );
  }
  if (
    renderStats.removedLinkAttributes !== EXPECTED_REMOVED_LINK_ATTRIBUTE_COUNT
  ) {
    fail(
      '被移除的链接属性列表数量不符合审计结果：' +
        renderStats.removedLinkAttributes +
        '，预期 ' +
        EXPECTED_REMOVED_LINK_ATTRIBUTE_COUNT
    );
  }
  if (
    renderStats.removedMarkdownAttributes !==
    EXPECTED_REMOVED_MARKDOWN_ATTRIBUTE_COUNT
  ) {
    fail(
      '被移除的 markdown HTML 属性数量不符合审计结果：' +
        renderStats.removedMarkdownAttributes +
        '，预期 ' +
        EXPECTED_REMOVED_MARKDOWN_ATTRIBUTE_COUNT
    );
  }
  const manifest = buildManifest(
    pages,
    collected.assets,
    collected.imageReferences,
    renderStats
  );
  return {
    pages,
    assets: collected.assets,
    imageReferences: collected.imageReferences,
    manifest
  };
}

function validateManifestPathList(root, paths, label) {
  if (!Array.isArray(paths)) {
    fail('旧导入清单的 ' + label + ' 不是数组。');
  }
  const seen = new Set();
  for (const relativePath of paths) {
    if (
      typeof relativePath !== 'string' ||
      path.posix.isAbsolute(relativePath) ||
      path.win32.isAbsolute(relativePath)
    ) {
      fail('旧导入清单包含不安全的 ' + label + ' 路径：' + String(relativePath));
    }
    const normalized = path.posix.normalize(toPosix(relativePath));
    if (
      normalized === '.' ||
      normalized.startsWith('../') ||
      normalized === '..' ||
      normalized !== toPosix(relativePath)
    ) {
      fail('旧导入清单包含不安全的 ' + label + ' 路径：' + relativePath);
    }
    if (seen.has(relativePath)) {
      fail('旧导入清单包含重复的 ' + label + ' 路径：' + relativePath);
    }
    seen.add(relativePath);
    safeResolve(root, relativePath);
  }
}

function readExistingManifest() {
  const contentExists = fs.existsSync(CONTENT_ROOT);
  const assetExists = fs.existsSync(ASSET_ROOT);
  const manifestExists = fs.existsSync(MANIFEST_PATH);
  if (!contentExists && !assetExists && !manifestExists) {
    return null;
  }
  if (!manifestExists) {
    fail(
      '拒绝清理未被导入清单标记的 CS61B 输出目录：' +
        CONTENT_ROOT +
        ' / ' +
        ASSET_ROOT
    );
  }
  if (!fs.lstatSync(MANIFEST_PATH).isFile()) {
    fail('CS61B 导入清单不是普通文件：' + MANIFEST_PATH);
  }
  let manifest;
  try {
    manifest = JSON.parse(readUtf8(MANIFEST_PATH));
  } catch (error) {
    fail('无法解析旧 CS61B 导入清单：' + error.message);
  }
  if (
    !manifest ||
    manifest.marker !== MANIFEST_MARKER ||
    manifest.version !== MANIFEST_VERSION ||
    !manifest.destination ||
    manifest.destination.contentRoot !==
      toPosix(path.relative(REPO_ROOT, CONTENT_ROOT)) ||
    manifest.destination.assetRoot !==
      toPosix(path.relative(REPO_ROOT, ASSET_ROOT)) ||
    manifest.destination.assetUrlPrefix !== ASSET_URL_PREFIX
  ) {
    fail('旧 CS61B 导入清单的所有权或版本不匹配，拒绝清理。');
  }
  if (!Array.isArray(manifest.pages) || !Array.isArray(manifest.assets)) {
    fail('旧 CS61B 导入清单缺少 pages/assets 数组，拒绝清理。');
  }
  validateManifestPathList(
    CONTENT_ROOT,
    manifest.pages.map((page) => page && page.output),
    '页面'
  );
  validateManifestPathList(ASSET_ROOT, manifest.assets, '资源');
  return manifest;
}

function removeGeneratedFile(root, relativePath) {
  const target = safeResolve(root, relativePath);
  if (!fs.existsSync(target)) {
    return;
  }
  const stat = fs.lstatSync(target);
  if (stat.isDirectory()) {
    fail('旧导入清单将目录列为文件，拒绝删除：' + target);
  }
  fs.unlinkSync(target);
}

function removeEmptyDirectories(root) {
  if (!fs.existsSync(root)) {
    return;
  }
  if (!fs.lstatSync(root).isDirectory()) {
    fail('输出根路径不是目录：' + root);
  }
  function visit(directory) {
    const entries = fs
      .readdirSync(directory, { withFileTypes: true })
      .sort((left, right) => compareStrings(left.name, right.name));
    for (const entry of entries) {
      if (entry.isDirectory()) {
        visit(path.join(directory, entry.name));
      }
    }
    if (fs.readdirSync(directory).length === 0) {
      fs.rmdirSync(directory);
    }
  }
  visit(root);
}

function removePreviousOutput(previous) {
  if (!previous) {
    return;
  }
  for (const page of previous.pages) {
    removeGeneratedFile(CONTENT_ROOT, page.output);
  }
  for (const asset of previous.assets) {
    removeGeneratedFile(ASSET_ROOT, asset);
  }
  removeGeneratedFile(CONTENT_ROOT, '.cs61b-import-manifest.json');
  removeEmptyDirectories(CONTENT_ROOT);
  removeEmptyDirectories(ASSET_ROOT);
}

function writeGeneratedFile(root, relativePath, contents) {
  const target = safeResolve(root, relativePath);
  if (fs.existsSync(target) && fs.lstatSync(target).isDirectory()) {
    fail('生成目标是目录，拒绝覆盖：' + target);
  }
  if (fs.existsSync(target) && fs.lstatSync(target).isSymbolicLink()) {
    fail('生成目标是符号链接，拒绝覆盖：' + target);
  }
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, contents, 'utf8');
}

function copyGeneratedAsset(asset) {
  const source = safeResolve(SOURCE_DOCS_ROOT, asset.sourcePath);
  const target = safeResolve(ASSET_ROOT, asset.path);
  if (!fs.existsSync(source) || !fs.statSync(source).isFile()) {
    fail('复制前找不到源资源：' + source);
  }
  if (fs.existsSync(target) && fs.lstatSync(target).isDirectory()) {
    fail('生成资源目标是目录，拒绝覆盖：' + target);
  }
  if (fs.existsSync(target) && fs.lstatSync(target).isSymbolicLink()) {
    fail('生成资源目标是符号链接，拒绝覆盖：' + target);
  }
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.copyFileSync(source, target);
}

function writeManifest(manifest) {
  writeGeneratedFile(
    CONTENT_ROOT,
    '.cs61b-import-manifest.json',
    JSON.stringify(manifest, null, 2) + '\n'
  );
}

export function importCs61b() {
  const plan = buildPlan();
  const previous = readExistingManifest();
  removePreviousOutput(previous);
  for (const page of plan.pages) {
    writeGeneratedFile(
      CONTENT_ROOT,
      toPosix(path.relative(CONTENT_ROOT, page.outputAbsolute)),
      page.content
    );
  }
  for (const asset of plan.assets) {
    copyGeneratedAsset(asset);
  }
  writeManifest(plan.manifest);
  return plan;
}

function isMainModule() {
  return (
    process.argv[1] &&
    path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
  );
}

if (isMainModule()) {
  try {
    const plan = importCs61b();
    console.log(
      'CS61B import complete: ' +
        plan.pages.length +
        ' pages, ' +
        plan.assets.length +
        ' assets, ' +
        plan.imageReferences +
        ' image references.'
    );
  } catch (error) {
    console.error('CS61B import failed: ' + error.message);
    process.exitCode = 1;
  }
}

export {
  ASSET_ROOT,
  ASSET_URL_PREFIX,
  ATTRIBUTION_END,
  ATTRIBUTION_START,
  CONTENT_ROOT,
  IMPORT_MARKER,
  MANIFEST_PATH,
  NEW_DOCS_URL_PREFIX,
  OLD_DOCS_URL_PREFIX,
  REPO_ROOT,
  SOURCE_DOCS_ROOT,
  SOURCE_ROOT,
  isExternalUrl,
  splitUrlSuffix
};
